### ISSUE TITLE
passing external parameters to payment.

### ISSUE THREAD

**Issue by staskuban** [AlexVangelov/billing-js#4]
Any doc  or any example?

**Comment by AlexVangelov** [comment]
Payment has a TS friendly `.state` property that can be used to attach some data.
`<item>.state // Unused instance variable available for UI purposes`
https://github.com/AlexVangelov/billing-js/blob/master/samples/browser/angular2/src/widget/paymentForm.html#L6

What is the use case?

**Comment by staskuban** [comment]
Thanx, i need passing some transaction data in backend. In my case - billing frontend not implemented

**Comment by AlexVangelov** [comment]
For backend use with direct access to some DB,
I would wrap the "promises" branch of the library inside something like https://www.npmjs.com/package/sync
This way changing the bill will wait for the transaction to complete and re-calculate the totals before continuing.
You can still use payment.state to keep the extra data like externalPaymentId and implement a store that is taking care of that property on save.
https://github.com/AlexVangelov/billing-js/blob/promises/src/extras/store/dynamoDbStore/index.ts#L58
